basePath: /user
definitions:
  model.User:
    properties:
      address:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: User API documentation
  version: 1.0.0
paths:
  /:
    get:
      description: get all users
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "404":
          description: Not Found
          schema:
            type: object
      summary: Get all users
      tags:
      - Users
swagger: "2.0"
